openapi: 3.0.3
info:
  title: Flask-shoppee
  description: used to access data from the database
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Local development server
paths:
  /api/products:
    get:
      summary: Get all products
      responses:
        '200':
          description: Successful response
    post:
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
                password:
                  type: string
                quantity:
                  type: integer
                price:
                  type: number
                category:
                  type: string
                best_before:
                  type: string
                cat:
                  type: integer
                desc:
                  type: string
      responses:
        '201':
          description: Product created successfully
  /api/products/{id}:
    get:
      summary: Get a product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
    put:
      summary: Update a product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
                password:
                  type: string
                quantity:
                  type: integer
                price:
                  type: number
                category:
                  type: string
                best_before:
                  type: string
                cat:
                  type: integer
                desc:
                  type: string
      responses:
        '201':
          description: Product name changed successfully
    delete:
      summary: Delete a product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '201':
          description: Product deleted successfully

  /api/categories:
    get:
      summary: Get all categories
      responses:
        '200':
          description: Successful response
    post:
      summary: Create a new category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                desc:
                  type: string
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Category created successfully
  /api/categories/{id}:
    get:
      summary: Get a category by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
    put:
      summary: Update a category by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
                password:
                  type: string
                quantity:
                  type: integer
                price:
                  type: number
                category:
                  type: string
                best_before:
                  type: string
                cat:
                  type: integer
                desc:
                  type: string
      responses:
        '201':
          description: Category name changed successfully
    delete:
      summary: Delete a category by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '201':
          description: Category deleted successfully
